apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-apache-site-config
data:
  DB_HOST: "127.0.0.1"
  DB_PORT: "3306"
  DB_NAME: "cleaning_service"
  SMTP_HOST: "smtp.example.com"
  SMTP_PORT: "587"
  SMTP_FROM_EMAIL: "no-reply@your-cleaning-business.com"
  SMTP_TO_EMAIL: "info@your-cleaning-business.com"
  SMTP_SECURE: "tls"
  SMTP_USE_PHP_MAIL: "true"
