apiVersion: v1
kind: Secret
metadata:
  name: simple-apache-site-secret
type: Opaque
data:
  SMTP_USER: "eW91ci1zbXRwLXVzZXI="
  SMTP_PASS: "eW91ci1zbXRwLXBhc3M="
  DB_USER: "ZGJ1c2Vy"
  DB_PASS: "ZGJwYXNz"
